art = {
    "http://www.artinstitutes.edu/miami": "Miami International University of Art & Design",
    "http://www.artinstitutes.edu/atlanta": "The Art Institute of Atlanta",
    "http://www.artinstitutes.edu/decatur": "The Art Institute of Atlanta-Decatur, a branch of The Art Institute of Atlanta",
    "http://www.artinstitutes.edu/austin": "The Art Institute of Austin, a branch of The Art Institute of Houston",
    "http://www.artinstitutes.edu/hollywood": "The Art Institute of California-Hollywood, a campus of Argosy University",
    "http://www.artinstitutes.edu/inlandempire": "The Art Institute of California-Inland Empire, a campus of Argosy University",
    "http://www.artinstitutes.edu/losangeles": "The Art Institute of California-Los Angeles, a campus of Argosy University",
    "http://www.artinstitutes.edu/orangecounty": "The Art Institute of California-Orange County, a campus of Argosy University",
    "http://www.artinstitutes.edu/sacramento": "The Art Institute of California-Sacramento, a campus of Argosy University",
    "http://www.artinstitutes.edu/sandiego": "The Art Institute of California-San Diego, a campus of Argosy University",
    "http://www.artinstitutes.edu/sanfrancisco": "The Art Institute of California-San Francisco, a campus of Argosy University",
    "http://www.artinstitutes.edu/siliconvalley": "The Art Institute of California-Silicon Valley, a campus of Argosy University",
    "http://www.artinstitutes.edu/charleston": "The Art Institute of Charleston, a branch of The Art Institute of Atlanta",
    "http://www.artinstitutes.edu/charlotte": "The Art Institute of Charlotte, a campus of South University",
    "http://www.artinstitutes.edu/denver": "The Art Institute of Colorado",
    "http://www.artinstitutes.edu/dallas": "The Art Institute of Dallas, a campus of South University",
    "http://www.artinstitutes.edu/fortlauderdale": "The Art Institute of Fort Lauderdale",
    "http://www.artinstitutes.edu/fort-worth": "The Art Institute of Fort Worth, a campus of South University",
    "http://www.artinstitutes.edu/houston": "The Art Institute of Houston",
    "http://www.artinstitutes.edu/houston-north": "The Art Institute of Houston - North, a branch of The Art Institute of Houston",
    "http://www.artinstitutes.edu/indianapolis": "The Art Institute of Indianapolis",
    "http://www.artinstitutes.edu/jacksonville": "The Art Institute of Jacksonville, a branch of Miami International University of Art &amp; Design",
    "http://www.artinstitutes.edu/lasvegas": "The Art Institute of Las Vegas",
    "http://www.artinstitutes.edu/detroit": "The Art Institute of Michigan",
    "http://www.artinstitutes.edu/troy": "The Art Institute of Michigan - Troy",
    "http://www.artinstitutes.edu/newyork": "The Art Institute of New York City",
    "http://www.artinstitutes.edu/cincinnati": "The Art Institute of Ohio - Cincinnati",
    "http://www.artinstitutes.edu/philadelphia": "The Art Institute of Philadelphia",
    "http://www.artinstitutes.edu/phoenix": "The Art Institute of Phoenix",
    "http://www.artinstitutes.edu/pittsburgh": "The Art Institute of Pittsburgh",
    "http://www.aionline.edu": "The Art Institute of Pittsburgh - Online Division",
    "http://www.artinstitutes.edu/portland": "The Art Institute of Portland",
    "http://www.artinstitutes.edu/raleigh-durham": "The Art Institute of Raleigh-Durham, a campus of South University",
    "http://www.artinstitutes.edu/saltlakecity": "The Art Institute of Salt Lake City",
    "http://www.artinstitutes.edu/san-antonio": "The Art Institute of San Antonio, a branch of The Art Institute of Houston",
    "http://www.artinstitutes.edu/seattle": "The Art Institute of Seattle",
    "http://www.artinstitutes.edu/st-louis": "The Art Institute of St. Louis",
    "http://www.artinstitutes.edu/tampa": "The Art Institute of Tampa, a branch of Miami International University of Art &amp; Design",
    "http://www.artinstitutes.edu/nashville": "The Art Institute of Tennessee - Nashville, a branch of The Art Institute of Atlanta",
    "http://www.artinstitutes.edu/tucson": "The Art Institute of Tucson",
    "http://www.artinstitutes.edu/vancouver": "The Art Institute of Vancouver",
    "http://www.artinstitutes.edu/virginia-beach": "The Art Institute of Virginia Beach, a branch of The Art Institute of Atlanta",
    "http://www.artinstitutes.edu/washington-dulles": "The Art Institute of Washington - Dulles, a branch of The Art Institute of Atlanta",
    "http://www.artinstitutes.edu/arlington": "The Art Institute of Washington, a branch of The Art Institute of Atlanta",
    "http://www.artinstitutes.edu/milwaukee": "The Art Institute of Wisconsin",
    "http://www.artinstitutes.edu/york": "The Art Institute of York - Pennsylvania",
    "http://www.artinstitutes.edu/kansascity": "The Art Institutes International - Kansas City",
    "http://www.artinstitutes.edu/minneapolis": "The Art Institutes International Minnesota",
    "http://www.artinstitutes.edu/chicago": "The Illinois Institute of Art - Chicago",
    "http://www.artinstitutes.edu/schaumburg": "The Illinois Institute of Art - Schaumburg",
    "http://www.artinstitutes.edu/tinleypark": "The Illinois Institute of Art - Tinley Park",
    "http://www.artinstitutes.edu/boston": "The New England Institute of Art",
}
